robot:
  type: uf::robot
  id: "uf_robot"
  robot_dof: 6
  control_space: "joint"
  robot_ip: "192.168.1.68"
  gripper_type: 1
  start_joints: [0, 0, -90, 0, 90, 0]

# make sure to edit with your correct configurations!
teleop:
  type: uf::gello_teleop
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAJZYC7-if00-port0"
  joint_ids: [1, 2, 4, 5, 6, 7]
  joint_signs: [1, 1, -1, 1, 1, 1]
  start_joints: [0, 0, -90, 0, 90, 0]
  gripper_id: 8
  torque_joint_ids: [3]

dataset:
  # root of local repo: /home/<user_name>/.cache/huggingface/lerobot (default)
  root: "/home/uf/Data/lerobot_datas/record/ufactory/xarm6_gello_datas"
  repo_id: "ufactory/xarm6_gello_datas"
  single_task: "Pick up the purple grape and drop into the box on the left."
  fps: 30
  episode_time_s: 60  # max duration for one episode
  reset_time_s: 20    # time for resetting env between episodes
  push_to_hub: False
