robot:
  type: uf::multiple_robot
  id: "multiple_uf_robots"
  async_connect: True
  async_configure: True
  async_action: False
  robots:
    left:
      type: uf::robot
      id: "left_uf_robot"
      robot_dof: 6
      control_space: "cartesian"
      robot_ip: "192.168.1.29"
      gripper_type: 2
      max_linear_velocity: 200
      start_joints: [-14.7, 25.6, -49.6, -282.5, 95.9, -65.9]
      start_tcp_pose: [400, 0, 150, -90, 0, 0]
      cameras:
        fisheye:
          type: opencv
          index_or_path: "/dev/v4l/by-id/usb-XVisio_Technology_XVisio_vSLAM_250801DR48FB26001379-video-index0"
          width: 1280
          height: 1280
          fps: 100
          fourcc: "YUYV"
    right:
      type: uf::robot
      id: "right_uf_robot"
      robot_dof: 6
      control_space: "cartesian"
      robot_ip: "192.168.1.83"
      gripper_type: 2
      max_linear_velocity: 200
      start_joints: [14.5, 25.5, -49.6, -76.8, 95.9, 66.6]
      start_tcp_pose: [400, 0, 150, 90, 0, 0]
      cameras:
        fisheye:
          type: opencv
          index_or_path: "/dev/v4l/by-id/usb-XVisio_Technology_XVisio_vSLAM_250801DR48FB26001396-video-index0"
          width: 1280
          height: 1280
          fps: 100
          fourcc: "YUYV"

# make sure to edit with your correct configurations!
teleop:
  type: uf::multiple_umi_teleop
  id: "multiple_teleops"
  teleops:
    left:
      type: uf::umi_teleop
      serial_number: "250801DR48FP26001318"
      use_vive_tracker: False
      vive_tracker_id: "LHR-555DC7BF"
      use_gripper: True
      tracker_to_robot_eef: [0, 0, 0, 0, 0, -90]
      robot_base_pose: [400, 0, 150, -90, 0, 0]
    right:
      type: uf::umi_teleop
      serial_number: "250801DR48FP26001295"
      use_vive_tracker: False
      vive_tracker_id: "LHR-2425BAD3"
      use_gripper: True
      tracker_to_robot_eef: [0, 0, 0, 0, 0, -90]
      robot_base_pose: [400, 0, 150, 90, 0, 0]

dataset:
  # root of local repo: /home/<user_name>/.cache/huggingface/lerobot (default)
  root: "/home/uf/Data/lerobot_datas/record/ufactory/dual_xarm6_umi_datas"
  repo_id: "ufactory/dual_xarm6_umi_datas"
  single_task: "Pick up the purple grape and drop into the box on the left."
  fps: 60
  episode_time_s: 60  # max duration for one episode
  reset_time_s: 20    # time for resetting env between episodes
  num_episodes: 100
  push_to_hub: False


